#ifndef __SIRTET_CONST_H__
#define __SIRTET_CONST_H__

#define GAME_BOARD_MARGIN		6
#define CELL_GRID_W				32
#define GAME_BOARD_W			10*CELL_GRID_W
#define GAME_BOARD_H			14*CELL_GRID_W
#define CONTROL_STAT_BOARD_W	20

#define MAIN_BOARD_W			GAME_BOARD_MARGIN*2 + GAME_BOARD_W + CONTROL_STAT_BOARD_W
#define MAIN_BOARD_H			GAME_BOARD_MARGIN*2 + GAME_BOARD_H

#endif // __SIRTET_CONST_H__